Added-PR-template
Feminine-Divine/periodo pull request #15
Opened 2021-02-28 17:38 UTC by 96RadhikaJadhav

This PR will resolve issue #2 .

2021-02-28 19:25 UTC, khushishikhu requested changes

2021-02-28 19:25 UTC, khushishikhu commented on .github/PR_template.md
> +#### Issue Number
```suggestion
#### Description
```
remove this line

2021-02-28 19:25 UTC, khushishikhu commented on .github/PR_template.md
> +fixes #
```suggestion
Issue FIXES #
```

2021-02-28 19:28 UTC, khushishikhu commented
@96RadhikaJadhav I have suggested few changes rest is perfect. And right now I can't merge it as the coding period isn't started yet. First you will get assigned to that issue and the this PR will be considered for evaluation.

2021-03-08 15:33 UTC, khushishikhu commented
@96RadhikaJadhav I have requested some changes here. Please do that changes and rest is all perfect.

2021-03-09 16:53 UTC, 96RadhikaJadhav commented
> @96RadhikaJadhav I have requested some changes here. Please do that changes and rest is all perfect.

@khushishikhu  Done.

2021-03-09 23:47 UTC, khushishikhu requested changes

2021-03-09 23:47 UTC, khushishikhu commented on .github/pull_request_template.md
> +Iusse FIXES #
```suggestion
Issue FIXES #
```

2021-03-09 23:47 UTC, khushishikhu commented on .github/pull_request_template.md
> +A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
@96RadhikaJadhav please comment out the statement of every description

2021-03-10 13:31 UTC, khushishikhu approved these changes

2021-03-10 13:33 UTC, merged