fixed the bug Text in 'AboutUs' page disappears in desktop mode
Feminine-Divine/periodo pull request #164
Opened 2021-04-01 13:32 UTC by satavshreya

#### Description
Issue FIXES #162 

//MADE CSS CHANGES://
.topline{
  display: flex;
  justify-content: center;
  font-weight: bold;
  margin-top: 0px;
  padding-top: 20px;
  color: #A0616A;
  text-transform: uppercase;
  background-color: #181818;
}
.subline{
  display: flex;
  margin-top: -18px;
  padding-top: 20px;
  justify-content: center;
  color: white;
  background-color: #181818;
  
}

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)

#### Test plan (OPTIONAL)

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

![2021-04-01 (2)](https://user-images.githubusercontent.com/61575173/113300869-04925b80-931c-11eb-90ef-26802b7874c9.png)
![2021-04-01 (5)](https://user-images.githubusercontent.com/61575173/113300876-05c38880-931c-11eb-9fe7-880af0d3a344.png)

 The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(GirlScript Summer of Code 2021)

2021-04-01 13:32 UTC, satavshreya commented
@khushishikhu @Aaishpra please review this one

2021-04-02 02:05 UTC, Aaishpra requested changes
Please check my feedback below

2021-04-02 02:05 UTC, Aaishpra commented on periodo/components/about/aboutstyle.module.css
> +    position:relative ;
why did you remove space from here? please add it back

2021-04-02 02:05 UTC, Aaishpra commented on periodo/components/about/aboutstyle.module.css
> -  padding-bottom: 20px;
Was removing this necessary

2021-04-02 02:05 UTC, Aaishpra commented on periodo/components/about/aboutstyle.module.css
> -  padding-left: 10px;
here too same as above

2021-04-02 07:53 UTC, satavshreya commented
@Aaishpra I have made the respective changes now what has to be the next step do i have to make a new pull request? or just push changes into my local newbranch?

2021-04-02 08:13 UTC, Aaishpra commented
Just push commits in this PR only no need for new PR

2021-04-02 09:45 UTC, satavshreya commented
@Aaishpra  pushed all of it Do let me know

2021-04-02 16:12 UTC, khushishikhu approved these changes
@satavshreya LGTM!! Thank you for your contribution.

2021-04-02 16:13 UTC, merged

2021-04-02 16:27 UTC, satavshreya commented
Happy to contribute to this :) Want to keep on contributing and really shape Periodo as a best project!