Add local setup instructions
Feminine-Divine/periodo pull request #17
Opened 2021-03-08 10:59 UTC by mdPial

Fixes #1 
I have added instructions to setup the project locally. Please check If I need to change or add anything.

2021-03-08 15:45 UTC, khushishikhu requested changes

2021-03-08 15:45 UTC, khushishikhu commented on README.md
> +- **Fork the repository:** Click the fork button of above.
```suggestion
- **Fork the repository:** Click the fork button.
```

2021-03-08 15:45 UTC, khushishikhu commented on README.md
> +- **Clone forked repository:** If you are using *Windows OS* use `Git Bash` to run all commands below.
```suggestion
- **Clone forked repository:** If you are using *Windows OS* use `Git Bash` to run all commands given below.
```

2021-03-08 15:45 UTC, khushishikhu commented on README.md
> +    yarn install
```suggestion
    yarn install
    or
    npm install
```

2021-03-08 15:45 UTC, khushishikhu commented on README.md
> +    yarn dev
```suggestion
    yarn dev
    or 
    npm run dev
```

2021-03-08 15:48 UTC, khushishikhu commented
@mdPial Thank you so much for this. I really liked the way you have written the Instructions. We really appreciate your efforts. I have suggested some changes , Just do add all these. And I will happily merge this PR

2021-03-08 16:27 UTC, mdPial commented
Thank you for detailed guidelines. I have updated.

2021-03-08 17:25 UTC, Aaishpra approved these changes

2021-03-08 17:27 UTC, Aaishpra commented
Great work @mdPial we will merge this after getting more instructions from GirlsScript side so that you can get your points for this PR😉

2021-03-08 18:45 UTC, khushishikhu approved these changes

2021-03-09 02:45 UTC, mdPial commented
Okay. Thank you 😄

2021-03-09 20:22 UTC, merged