Adding the demo project video link to the README
Feminine-Divine/periodo pull request #18
Opened 2021-03-08 16:19 UTC by SandeepKrSuman

close #11 

> 
![Screenshot (238)](https://user-images.githubusercontent.com/54541515/110348773-038d4780-8058-11eb-9031-8fdd46bb72d2.png)

2021-03-08 21:21 UTC, khushishikhu requested changes

2021-03-08 21:21 UTC, khushishikhu commented on README.md
> +### Demo Project Video : :tv: https://youtu.be/3dxa599SPT4
```suggestion
### Project's Demo Video : :tv: https://youtu.be/3dxa599SPT4
```

2021-03-08 21:22 UTC, khushishikhu commented
@SandeepKrSuman Make this change. Rest is all good. Thank you for your efforts. Keep Coding

2021-03-08 21:37 UTC, SandeepKrSuman commented
I have made the changes. Can you please check once and merge the PR...

2021-03-09 06:46 UTC, khushishikhu commented
@SandeepKrSuman Thank you. LGTM!!.

2021-03-09 06:46 UTC, khushishikhu approved these changes

2021-03-10 08:37 UTC, merged