issue_templates added in .github
Feminine-Divine/periodo pull request #23
Opened 2021-03-09 03:07 UTC by luckykumarirai

I have added the issue templates in the  .github folder.
close #4

2021-03-09 06:54 UTC, khushishikhu requested changes

2021-03-09 06:54 UTC, khushishikhu commented on periodo/.github/ISSUE_TEMPLATE/bug.md
> +labels: ''
```suggestion

```

2021-03-09 06:54 UTC, khushishikhu commented on periodo/.github/ISSUE_TEMPLATE/bug.md
> +assignees: ''
```suggestion

```

2021-03-09 06:54 UTC, khushishikhu commented on periodo/.github/ISSUE_TEMPLATE/bug.md
> +A clear and concise description of what the bug is.
Comment out the statement in every description part of the Issue template

2021-03-10 14:38 UTC, Aaishpra commented
@luckykumarirai can you add the suggested changes so that this PR can be merged

2021-03-10 14:47 UTC, luckykumarirai commented
sure I will

2021-03-11 05:28 UTC, khushishikhu approved these changes

2021-03-11 05:30 UTC, khushishikhu commented
@luckykumarirai LGTM!! Thank you so much for making the template. Keep contributing.

2021-03-11 06:00 UTC, merged