integrate google maps using react
Feminine-Divine/periodo pull request #336
Opened 2021-05-21 15:56 UTC by subhangi2731

#### Description

For adding hospitals list, I will do integrate google maps in react so that it provide directions to the hospital address
and show a route to that and to provide live updates on distance and location.

Issue FIXES #324

#### Describe the changes you've made

I have made Googlemap.js in react for giving the location in case of emergency and modified Gynac.js and package.json files and thus integrated google maps for location in react.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Checklist

- [x] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

2021-05-21 15:57 UTC, subhangi2731 commented
@khushishikhu please review and merge my pr

2021-05-21 16:11 UTC, subhangi2731 commented
@khushishikhu I will add it now

2021-05-22 06:14 UTC, subhangi2731 commented
![Screenshot from 2021-05-22 10-50-00](https://user-images.githubusercontent.com/53938490/119216722-fc23f900-baf2-11eb-9863-20bea824b024.png)
![Screenshot from 2021-05-22 10-50-21](https://user-images.githubusercontent.com/53938490/119216731-08a85180-baf3-11eb-9081-5e2d99688a60.png)

2021-05-22 06:14 UTC, subhangi2731 commented
@khushishikhu please merge my pr

2021-05-22 06:49 UTC, khushishikhu requested changes

2021-05-22 06:49 UTC, khushishikhu commented on periodo/components/Gynae/GoogleMap.js
> +  apiKey: ('API_KEY')
```suggestion
  apiKey: ('MAP_API_KEY')
```

2021-05-22 06:51 UTC, khushishikhu commented
@subhangi2731 Update your branch

2021-05-22 08:56 UTC, subhangi2731 commented
@khushishikhu done please merge the pr

2021-05-22 09:00 UTC, merged