Adding a quiz page
Feminine-Divine/periodo pull request #88
Opened 2021-03-14 08:54 UTC by anshika208

#### Description
Issue FIXES #21 
fixes #21 

#### Describe the changes you've made
 i have added a new quiz page in a new few folder named analysis. the quiz page contains navbar and 5 questions which will  come one after the other in a box form.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
'NA'

#### Additional context (OPTIONAL)

![quiz1](https://user-images.githubusercontent.com/54038386/111062532-5f7c2400-84cf-11eb-9686-0d35de159406.png)
![quiz4](https://user-images.githubusercontent.com/54038386/111062610-ecbf7880-84cf-11eb-9efd-9f2a11ad61d5.jpeg)
![quiz3](https://user-images.githubusercontent.com/54038386/111062614-f1842c80-84cf-11eb-9358-27b765d884ec.jpeg)

#### Test plan (OPTIONAL)

#### Checklist

- [x ] I have added my name in the contributors list at the end of README.md file.
- [x ] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
- [ x] I have added tests to cover my changes.
- [ x] All new and existing tests passed.
- [ x] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

2021-03-14 08:56 UTC, anshika208 commented
@khushishikhu @Aaishpra i have submitted the pr for adding a quiz page. please have a look!

2021-03-14 09:16 UTC, Aaishpra requested changes
Just a little grammatical error for now, Will review this PR more precisely once i get free.

2021-03-14 09:16 UTC, Aaishpra commented on periodo/components/analysis/Analysis.js
> +			questionText: 'Is your periods regular?',
Are your periods regular?

2021-03-14 11:15 UTC, anshika208 commented on periodo/components/analysis/Analysis.js
> +			questionText: 'Is your periods regular?',
sure .. i will look into this... thnku!!

2021-03-15 11:45 UTC, Aaishpra approved these changes
LGTM Loved your work @anshika208 
But from next time try to create PR from different branch

2021-03-15 11:46 UTC, merged